
import React, { useState, useCallback, useEffect, useRef } from 'react';
import { tailorResume } from './services/geminiService';
import { parseResumeFile } from './services/fileParser';
import Header from './components/Header';
import InputPanel from './components/InputPanel';
import OutputPanel from './components/OutputPanel';
import HomePage from './components/HomePage';


interface RecentResume {
  name: string;
  content: string;
}

const TAILOR_LIMIT = 60;

// Helper to get date in YYYY-MM-DD format
const getTodayDateString = (): string => {
  const today = new Date();
  const year = today.getFullYear();
  const month = String(today.getMonth() + 1).padStart(2, '0');
  const day = String(today.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

const App: React.FC = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [userEmail, setUserEmail] = useState<string>('');
  const [resume, setResume] = useState<string>(''); // Parsed text
  const [resumeFile, setResumeFile] = useState<File | null>(null);
  const [jobDescription, setJobDescription] = useState<string>('');
  const [customPrompt, setCustomPrompt] = useState<string>('');
  const [promptIsAutoGenerated, setPromptIsAutoGenerated] = useState<boolean>(false);
  const [tailoredResume, setTailoredResume] = useState<string>('');
  const [tailoringAnalysis, setTailoringAnalysis] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [progress, setProgress] = useState<number>(0);
  const [isParsing, setIsParsing] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [recentResumes, setRecentResumes] = useState<RecentResume[]>([]);
  const [tailorCount, setTailorCount] = useState<number>(TAILOR_LIMIT);

  // Interactivity state
  const pasteButtonRef = useRef<HTMLButtonElement>(null);

  // Theme Management
  const [theme, setTheme] = useState<'light' | 'dark'>('light');

  useEffect(() => {
    const savedTheme = localStorage.getItem('ai-resume-tailor-theme') as 'light' | 'dark' | null;
    if (savedTheme) {
      setTheme(savedTheme);
    } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
      setTheme('dark');
    }
  }, []);

  useEffect(() => {
    const root = document.documentElement;
    if (theme === 'dark') {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
    localStorage.setItem('ai-resume-tailor-theme', theme);
  }, [theme]);

  const toggleTheme = () => {
    setTheme(prev => prev === 'light' ? 'dark' : 'light');
  };

  const abortControllerRef = useRef<AbortController | null>(null);

  // Load Recent Resumes for specific user
  useEffect(() => {
    if (!userEmail) return;
    try {
      const key = `ai-resume-tailor-resumes-${userEmail}`;
      const savedResumes = localStorage.getItem(key);
      if (savedResumes) {
        setRecentResumes(JSON.parse(savedResumes));
      } else {
        setRecentResumes([]);
      }
    } catch (err) {
      console.error('Failed to load recent resumes from localStorage:', err);
    }
  }, [userEmail]);

  // Load Usage Limit for specific user
  useEffect(() => {
    if (!userEmail) return;
    try {
      const key = `ai-resume-tailor-daily-usage-${userEmail}`;
      const savedUsage = localStorage.getItem(key);
      const today = getTodayDateString();

      if (savedUsage) {
        const { count, date } = JSON.parse(savedUsage);

        // If the saved date is today and the count is a valid number, use it
        if (date === today && typeof count === 'number' && !isNaN(count)) {
          setTailorCount(count);
        } else {
          // It's a new day or the data is malformed, so reset the limit
          setTailorCount(TAILOR_LIMIT);
          localStorage.setItem(key, JSON.stringify({ count: TAILOR_LIMIT, date: today }));
        }
      } else {
        // No usage data found, so initialize for today
        setTailorCount(TAILOR_LIMIT);
        localStorage.setItem(key, JSON.stringify({ count: TAILOR_LIMIT, date: today }));
      }
    } catch (err) {
      console.error('Failed to load tailor count from localStorage:', err);
      // On any error (e.g., parsing), reset to a safe default
      const today = getTodayDateString();
      const key = `ai-resume-tailor-daily-usage-${userEmail}`;
      setTailorCount(TAILOR_LIMIT);
      localStorage.setItem(key, JSON.stringify({ count: TAILOR_LIMIT, date: today }));
    }
  }, [userEmail]);


  const handleCustomPromptChange = (value: string) => {
    setCustomPrompt(value);
    setPromptIsAutoGenerated(false); // Any user edit makes the prompt non-automatic
  };

  const handleFileChange = useCallback(async (file: File | null) => {
    if (!file) {
      setResumeFile(null);
      setResume('');
      setError(null);
      // If the prompt was auto-generated, clear it when the file is removed
      if (promptIsAutoGenerated) {
        setCustomPrompt('');
        setPromptIsAutoGenerated(false);
      }
      return;
    }

    setIsParsing(true);
    setError(null);
    setResumeFile(file);

    try {
      const text = await parseResumeFile(file);
      setResume(text);

      const urlRegex = /(https?:\/\/|www\.)[^\s]+/g;
      const hasUrls = urlRegex.test(text);

      // If URLs are found and the prompt is empty or was auto-generated, set our message.
      if (hasUrls && (!customPrompt || promptIsAutoGenerated)) {
        setCustomPrompt("This resume contains links (e.g., portfolio, GitHub). For the best results, please paste the text content from any relevant links here so the AI can use that information.");
        setPromptIsAutoGenerated(true);
      } else if (!hasUrls && promptIsAutoGenerated) {
        // If a new file without URLs is chosen, clear the auto-generated prompt.
        setCustomPrompt('');
        setPromptIsAutoGenerated(false);
      }

      const newResume = { name: file.name, content: text };
      setRecentResumes(prevResumes => {
        const otherResumes = prevResumes.filter(r => r.name !== file.name);
        const updatedResumes = [newResume, ...otherResumes].slice(0, 2);
        try {
          if (userEmail) {
            localStorage.setItem(`ai-resume-tailor-resumes-${userEmail}`, JSON.stringify(updatedResumes));
          }
        } catch (err) {
          console.error('Failed to save recent resumes to localStorage:', err);
        }
        return updatedResumes;
      });

    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to parse file.');
      setResumeFile(null); // Clear file on parsing error
      setResume('');
    } finally {
      setIsParsing(false);
    }
  }, [customPrompt, promptIsAutoGenerated, userEmail]);


  const handleSelectRecentResume = useCallback((resumeToLoad: RecentResume) => {
    setResume(resumeToLoad.content);
    const file = new File([resumeToLoad.content], resumeToLoad.name, { type: 'text/plain' });
    setResumeFile(file);
    setError(null);

    const urlRegex = /(https?:\/\/|www\.)[^\s]+/g;
    const hasUrls = urlRegex.test(resumeToLoad.content);

    if (hasUrls && (!customPrompt || promptIsAutoGenerated)) {
      setCustomPrompt("This resume contains links (e.g., portfolio, GitHub). For the best results, please paste the text content from any relevant links here so the AI can use that information.");
      setPromptIsAutoGenerated(true);
    } else if (!hasUrls && promptIsAutoGenerated) {
      setCustomPrompt('');
      setPromptIsAutoGenerated(false);
    }
  }, [customPrompt, promptIsAutoGenerated]);

  const progressTimeoutRef = useRef<number | null>(null);

  const handleStopTailoring = useCallback(() => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
      abortControllerRef.current = null;
    }
    if (progressTimeoutRef.current) {
      clearTimeout(progressTimeoutRef.current);
    }
    setIsLoading(false);
    setProgress(0);
  }, []);

  const handleTailorResume = useCallback(async (overrideJobDescription?: string) => {
    const currentJobDescription = typeof overrideJobDescription === 'string' ? overrideJobDescription : jobDescription;

    if (tailorCount <= 0) {
      setError(`You have reached your daily limit of ${TAILOR_LIMIT} resume tailors.`);
      return;
    }
    if (!resume || !currentJobDescription) {
      setError('Please upload a resume file and provide the job description.');
      return;
    }

    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
    }

    const controller = new AbortController();
    abortControllerRef.current = controller;

    setIsLoading(true);
    setError(null);
    setTailoredResume('');
    setTailoringAnalysis('');
    setProgress(0);

    if (progressTimeoutRef.current) {
      clearTimeout(progressTimeoutRef.current);
    }

    const DURATION = 80000; // 80 seconds
    const MAX_SIMULATED_PROGRESS = 95;
    const startTime = Date.now();

    const updateProgress = () => {
      const elapsedTime = Date.now() - startTime;
      const progressValue = (elapsedTime / DURATION) * 100;

      if (progressValue >= MAX_SIMULATED_PROGRESS) {
        setProgress(MAX_SIMULATED_PROGRESS);
        return;
      }

      setProgress(progressValue);
      progressTimeoutRef.current = window.setTimeout(updateProgress, 100);
    };

    updateProgress();

    try {
      let fullResponse = '';
      const handleChunk = (chunk: string) => {
        fullResponse += chunk;
      };

      await tailorResume(
        resume,
        currentJobDescription,
        customPrompt,
        handleChunk,
        controller.signal
      );

      if (progressTimeoutRef.current) clearTimeout(progressTimeoutRef.current);
      setProgress(100);

      const analysisStartSeparator = '---ANALYSIS_START---';
      const analysisStartIndex = fullResponse.indexOf(analysisStartSeparator);

      if (analysisStartIndex !== -1) {
        const resumePart = fullResponse.substring(0, analysisStartIndex);
        const analysisPart = fullResponse
          .substring(analysisStartIndex + analysisStartSeparator.length)
          .replace(/---ANALYSIS_END---/g, '')
          .trim();
        setTailoredResume(resumePart);
        setTailoringAnalysis(analysisPart);
      } else {
        setTailoredResume(fullResponse);
        setTailoringAnalysis('');
      }


      const newCount = tailorCount - 1;
      setTailorCount(newCount);
      if (userEmail) {
        localStorage.setItem(`ai-resume-tailor-daily-usage-${userEmail}`, JSON.stringify({ count: newCount, date: getTodayDateString() }));
      }

      setTimeout(() => {
        setIsLoading(false);
        setProgress(0);
        abortControllerRef.current = null;
      }, 500);

    } catch (err) {
      if (progressTimeoutRef.current) clearTimeout(progressTimeoutRef.current);
      const message = err instanceof Error ? err.message : 'An unknown error occurred.';
      if (message === 'Tailoring stopped by user.') {
        setError(null);
      } else {
        setError(message);
      }
      setIsLoading(false);
      setProgress(0);
      abortControllerRef.current = null;
    }
  }, [resume, jobDescription, customPrompt, tailorCount, userEmail]);

  useEffect(() => {
    return () => {
      if (progressTimeoutRef.current) {
        clearTimeout(progressTimeoutRef.current);
      }
      if (abortControllerRef.current) {
        abortControllerRef.current.abort();
      }
    };
  }, []);

  const handleLogin = (email: string) => {
    setUserEmail(email);
    setIsLoggedIn(true);
  };

  if (!isLoggedIn) {
    return <HomePage onLogin={handleLogin} theme={theme} toggleTheme={toggleTheme} />;
  }

  return (
    <div className="min-h-screen bg-stone-50 dark:bg-slate-900 text-stone-800 dark:text-slate-200 font-sans flex flex-col transition-colors duration-300">
      <Header theme={theme} toggleTheme={toggleTheme} />
      <main className="container mx-auto px-4 py-8 flex-grow">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <InputPanel
            resumeFile={resumeFile}
            onFileChange={handleFileChange}
            isParsing={isParsing}
            jobDescription={jobDescription}
            setJobDescription={setJobDescription}
            customPrompt={customPrompt}
            setCustomPrompt={handleCustomPromptChange}
            onTailor={handleTailorResume}
            onStopTailor={handleStopTailoring}
            isLoading={isLoading}
            progress={progress}
            error={error}
            recentResumes={recentResumes}
            onSelectRecent={handleSelectRecentResume}
            tailorCount={tailorCount}
            tailoringAnalysis={tailoringAnalysis}
            pasteButtonRef={pasteButtonRef}
          />
          <OutputPanel
            tailoredResume={tailoredResume}
            isLoading={isLoading}
            setTailoredResume={setTailoredResume}
          />
        </div>
      </main>
    </div>
  );
};

export default App;
